=== geonetwork/core-geonetwork/web/src/main/webapp/WEB-INF/wro-sources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">
  <xs:element name="sources" type="sourcesType"/>
  <xs:complexType name="sourcesType">
    <xs:sequence>
      <xs:element type="includeType" name="include" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="requireType" name="require" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="declarativeType" name="declarative" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="includeType">
    <xs:annotation>
      <xs:documentation>
        Include another wro-source.xml file that contains elements to add to the model.
        Care must be taken to not duplicate group names in included files.

        By default the file attribute is relative to the file containing the include but the file
        attribute
        may also be a URL or be prefixed with classpath: to search the classpath for all instances
        with the provided name.

        Examples:

        classpath:wro-sources.xml  <!-- Find all load all files on the classpath called wro-sources.xml -->
        http://abc.com/wro-sources.xml <!-- load the resources file from the website abc.com -->
        ../wro-sources.xml <!-- find the wro-sources.xml in the parent directory of the included file -->

      </xs:documentation>
    </xs:annotation>
    <xs:attribute type="xs:string" name="file" use="required"/>
  </xs:complexType>

  <xs:complexType name="requireType">
    <xs:annotation>
      <xs:documentation>
        For each jsSource search the path provided and use the goog.require and goog.provide method
        calls in the javascript
        files to identify the dependencies between javascript files.
        For each js file a wro Group will be created which contains all dependencies required by
        that file. This allows one to
        write all the js files and simply include the one that is needed without needing to consider
        which dependencies that
        file has.

        For each cssSource search all subdirectories of the path provided and create a group from
        the name of each css or less
        file found.

        If a css file and a js file have the same name then they will be part of the same group.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element type="requireJsSourceType" name="jsSource" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="requireCssSourceType" name="cssSource" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
      <xs:annotation>
        <xs:documentation>
          pathOnDisk is only used when running unit tests or when running the maven build. it
          identifies the path to
          a resource relative the the root module. This value is added to the webappPath attribute
          when running in tests
          or in maven build to create a path to the directory to search.

          For example, even if the wro-sources.xml file is in the web/src/main/webResources/WEB-INF
          folder, the pathOnDisk
          should be web-ui/src/main/resources for the web-ui javascript files.

          Note: the webappPath contains the path required to load using ServletContext.getRealPath
          and the pathOnDisk
          is prefixed to that path to create a path for maven and junit tests

          Note: The value on this element can be overridded by the value on an individual jsSource
          element. This is simply
          intended to reduce redundant declarations.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="declarativeType">
    <xs:annotation>
      <xs:documentation>
        Create a single group with the given name and add each jsSource and cssSource in the order
        they are defined.
        No wild cards are currently accepted.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element type="declareJsSourceType" name="jsSource" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="declareCssSourceType" name="cssSource" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
      <xs:annotation>
        <xs:documentation>
          pathOnDisk is only used when running unit tests or when running the maven build. it
          identifies the path to
          a resource relative the the root module. This value is added to the webappPath attribute
          when running in tests
          or in maven build to create a path to the actual javascript file.

          For example, even if the wro-sources.xml file is in the web/src/main/webResources/WEB-INF
          folder, the pathOnDisk
          should be web-ui/src/main/resources for the web-ui javascript files.

          Note: the webappPath contains the path required to load using ServletContext.getRealPath
          and the pathOnDisk
          is prefixed to that path to create a path for maven and junit tests.

          Note: The value on this element can be overridded by the value on an individual jsSource
          element. This is simply
          intended to reduce redundant declarations.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="requireJsSourceType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element type="collectionType" name="notMinimized" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="webappPath" use="required">
      <xs:annotation>
        <xs:documentation>
          the path to the javascript file or the search directory that is used with running as a
          webapp. The path
          is resolved using ServletContext#getRealPath() to locate the actual file.

          For maven builds or junit tests this will be appended to pathOnDisk.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
      <xs:annotation>
        <xs:documentation>
          pathOnDisk is only used when running unit tests or when running the maven build. it
          identifies the path to
          a resource relative the the root module. This value is added to the webappPath attribute
          when running in tests
          or in maven build to create a path to the actual javascript file or search directory.

          For example, even if the wro-sources.xml file is in the web/src/main/webResources/WEB-INF
          folder, the
          pathOnDisk
          should be web-ui/src/main/resources for the web-ui javascript files.

          Note: the webappPath contains the path required to load using ServletContext.getRealPath
          and the pathOnDisk
          is prefixed to that path to create a path for maven and junit tests.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="declareJsSourceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="webappPath" use="required">
          <xs:annotation>
            <xs:documentation>
              the path to the javascript file or the search directory that is used with running as a
              webapp. The path
              is resolved using ServletContext#getRealPath() to locate the actual file.

              For maven builds or junit tests this will be appended to pathOnDisk.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
          <xs:annotation>
            <xs:documentation>
              pathOnDisk is only used when running unit tests or when running the maven build. it
              identifies the path to
              a resource relative the the root module. This value is added to the webappPath
              attribute when running in tests
              or in maven build to create a path to the actual javascript file or search directory.

              For example, even if the wro-sources.xml file is in the
              web/src/main/webResources/WEB-INF folder, the
              pathOnDisk
              should be web-ui/src/main/resources for the web-ui javascript files.

              Note: the webappPath contains the path required to load using
              ServletContext.getRealPath and the pathOnDisk
              is prefixed to that path to create a path for maven and junit tests.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:boolean" name="minimize" use="optional">
          <xs:annotation>
            <xs:documentation>
              if true or not present then the file will be passed all the minizing processors in the
              processing chain
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="requireCssSourceType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element type="collectionType" name="notMinimized" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="webappPath" use="required">
      <xs:annotation>
        <xs:documentation>
          the path to the javascript file or the search directory that is used with running as a
          webapp. The path
          is resolved using ServletContext#getRealPath() to locate the actual file.

          For maven builds or junit tests this will be appended to pathOnDisk.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
      <xs:annotation>
        <xs:documentation>
          pathOnDisk is only used when running unit tests or when running the maven build. it
          identifies the path to
          a resource relative the the root module. This value is added to the webappPath attribute
          when running in tests
          or in maven build to create a path to the actual css/less file or search directory.

          For example, even if the wro-sources.xml file is in the web/src/main/webResources/WEB-INF
          folder, the
          pathOnDisk
          should be web-ui/src/main/resources for the web-ui javascript files.

          Note: the webappPath contains the path required to load using ServletContext.getRealPath
          and the pathOnDisk
          is prefixed to that path to create a path for maven and junit tests.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="declareCssSourceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="webappPath" use="required">
          <xs:annotation>
            <xs:documentation>
              the path to the javascript file or the search directory that is used with running as a
              webapp. The path
              is resolved using ServletContext#getRealPath() to locate the actual file.

              For maven builds or junit tests this will be appended to pathOnDisk.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="pathOnDisk" use="optional">
          <xs:annotation>
            <xs:documentation>
              pathOnDisk is only used when running unit tests or when running the maven build. it
              identifies the path to
              a resource relative the the root module. This value is added to the webappPath
              attribute when running in tests
              or in maven build to create a path to the actual css/less file or search directory.

              For example, even if the wro-sources.xml file is in the
              web/src/main/webResources/WEB-INF folder, the
              pathOnDisk
              should be web-ui/src/main/resources for the web-ui javascript files.

              Note: the webappPath contains the path required to load using
              ServletContext.getRealPath and the pathOnDisk
              is prefixed to that path to create a path for maven and junit tests.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:boolean" name="minimize" use="optional">
          <xs:annotation>
            <xs:documentation>
              if true or not present then the file will be passed all the minizing processors in the
              processing chain
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="collectionType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element type="xs:string" name="file" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== geonetwork/core-geonetwork/web-ui/src/main/resources/WEB-INF/classes/web-ui-wro-sources.xml
<!--
  ~ Copyright (C) 2001-2016 Food and Agriculture Organization of the
  ~ United Nations (FAO-UN), United Nations World Food Programme (WFP)
  ~ and United Nations Environment Programme (UNEP)
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or (at
  ~ your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
  ~
  ~ Contact: Jeroen Ticheler - FAO - Viale delle Terme di Caracalla 2,
  ~ Rome - Italy. email: geonetwork@osgeo.org
  -->

<sources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../../../web/src/main/webapp/WEB-INF/wro-sources.xsd">
  <require pathOnDisk="web-ui/src/main/resources">
    <jsSource webappPath="/catalog/js/"/>
    <jsSource webappPath="/catalog/views/"/>
    <jsSource webappPath="/catalog/components/"/>
    <jsSource webappPath="/catalog/templates/"/>
    <cssSource webappPath="/catalog/views/"/>
    <cssSource webappPath="/catalog/style/"/>
    <cssSource webappPath="/catalog/lib/bootstrap-table/dist/bootstrap-table.min.css" />
  </require>
  <declarative name="lib" pathOnDisk="web-ui/src/main/resources">
    <jsSource webappPath="/catalog/lib/modernizr.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-3.7.1.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-migrate-mute.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-migrate-3.6.0.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/moment-with-locales.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/moment-timezone-with-data-1970-2030.min.js" minimize="false" />
    <jsSource webappPath="/catalog/lib/angular/angular.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular-filter.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular/angular-resource.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular/angular-route.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular/angular-sanitize.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular/angular-cookies.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular/angular-messages.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular-translate.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular-md5.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular.ext/hotkeys/hotkeys.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/angular.ext/bindHtml.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/buttons.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/datetimepicker.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/modal.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/position.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/slider.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/rating.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/tabs.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/typeahead.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/colorpicker/angularjs-color-picker.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/date.js"/>
    <jsSource webappPath="/catalog/lib/angular.ext/angular-floatThead.js"/>
    <jsSource webappPath="/catalog/lib/tinycolor.js"/>
    <jsSource webappPath="/catalog/lib/franc-min/franc-min.js"/>
    <jsSource webappPath="/catalog/lib/style/bootstrap/dist/js/bootstrap.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/proj4js-compressed.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/openlayers/ol.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/d3.v3.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/nv.d3.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jsonix/jsonix/Jsonix-min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.ui.widget.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.iframe-transport.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.fileupload.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.fileupload-process.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.fileupload-angular.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery.floatThead-slim.min.js"/>
    <jsSource webappPath="/catalog/lib/jquery.ext/jquery-ui-slider-1.13.2.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/typeahead.js/typeahead.bundle.js"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/tagsinput/bootstrap-tagsinput.min.js"
              minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/tagsinput/bootstrap-tagsinput-angular.js"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.fr.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.nl.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.az.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ca.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.cs.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.cy.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.da.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.de.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.es.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.fi.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.hy.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.is.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.it.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ka.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ko.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.pt.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ro.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.ru.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.sk.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.sv.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.uk.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap.ext/datepicker/bootstrap-datepicker.zh.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap-table/dist/bootstrap-table.min.js"
              minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap-table/dist/bootstrap-table-locale-all.min.js"
            minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap-table-angular.js"
              minimize="false"/>
    <jsSource webappPath="/catalog/lib/FileSaver/FileSaver.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/tableExport/tableExport.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap-table/dist/extensions/export/bootstrap-table-export.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.min.js" />
    <jsSource webappPath="/catalog/lib/zip/zip.js"/>
    <jsSource webappPath="/catalog/lib/zip/include.js"/>
    <jsSource webappPath="/catalog/lib/base64.js"/>
    <jsSource webappPath="/catalog/lib/lodash/lodash.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/recaptcha/angular-recaptcha.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/geohash.js"/>
    <jsSource webappPath="/catalog/lib/xml2json/xml2json.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/dom-to-image/dom-to-image.min.js" minimize="false"/>
  </declarative>
  <!-- Same as previous + olcesium -->
  <declarative name="lib3d" pathOnDisk="web-ui/src/main/resources">
    <jsSource webappPath="/catalog/lib/modernizr.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-3.7.1.min.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-migrate-mute.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/jquery-migrate-3.6.0.js" minimize="false"/>
    <jsSource webappPath="/catalog/lib/moment-with-locales.min.js" minimize="false"/>
