=== geonetwork/core-geonetwork/schemas/schema-labels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2001-2016 Food and Agriculture Organization of the
  ~ United Nations (FAO-UN), United Nations World Food Programme (WFP)
  ~ and United Nations Environment Programme (UNEP)
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or (at
  ~ your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
  ~
  ~ Contact: Jeroen Ticheler - FAO - Viale delle Terme di Caracalla 2,
  ~ Rome - Italy. email: geonetwork@osgeo.org
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="labels">
    <xs:annotation>
      <xs:documentation>A list of labels describing standard descriptors
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="element">
          <xs:annotation>
            <xs:documentation>A descriptor with label, definition, help text and
              suggestions
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="element">
    <xs:complexType>
      <xs:all>
        <xs:element ref="label" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>The descriptor label to display next
              to the field
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="btnLabel" type="xs:string" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Optional label to be addded to the add button.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="btnClass" type="xs:string" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Optional CSS class to be added to the add button.</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="description" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>The definition to be displayed in the help
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="help" minOccurs="0">
          <xs:annotation>
            <xs:documentation>More help (CDATA could be used to store HTML)
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="condition" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>CHECKME: Not really used ?</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="example" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Examples to be added to the help section
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="helper" minOccurs="0">
          <xs:annotation>
            <xs:documentation>List of suggestion to be displayed in edit mode to
              help populating the field. It's ussually common values for a
              field.
              More than one helper could be define if needed to match different
              scope of metadata (eg. metadata on dataset and metadata on
              service).
              In that case, a displayIf attribute is added to define when to
              display that helper list.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:all>
      <xs:attribute name="context" type="xs:NMTOKEN">
        <xs:annotation>
          <xs:documentation>Parent element name or full XPath</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="id" type="xs:decimal">
        <xs:annotation>
          <xs:documentation>An optional reference to the standard descriptor
            identifier.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="help" type="xs:string"/>
  <xs:element name="label" type="xs:string"/>
  <xs:element name="example" type="xs:string"/>

  <xs:element name="helper">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="option">
          <xs:annotation>
            <xs:documentation>Suggestion is an HTML option</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="rel" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of the element to be populated by the title
            attribute of the option. That parameter allows to update 2 fields in
            the editor at a time.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="relAtt" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of an attribute (eg. uom) to be populated by
            the title attribute of the option. That parameter allows to update 2
            fields in the editor at a time.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="sort" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Set this attribute to true to sort by alpha order.
            By default, the helpers are displayed in the order define in labels
            file.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="editorMode">
        <xs:annotation>
          <xs:documentation>By default, the list of suggestion is displayed in a
            combo next to the element.
            The layout may be customized by setting the editorMode attribute.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="radio">
              <xs:annotation>
                <xs:documentation>Simple radio displayed next to each other.
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="suggestion">
              <xs:annotation>
                <xs:documentation>Suggestion list. Preserve existing value, but does not allow to type value not provided in the list.
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="radio_withdesc">
              <xs:annotation>
                <xs:documentation>Radio button with label and the description
                  define in the title attribute.
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="radio_linebreak">
              <xs:annotation>
                <xs:documentation>Radio button with line break between each of
                  them (maybe better to use CSS to define this).
                </xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute ref="displayIf"/>
    </xs:complexType>
  </xs:element>

  <xs:attribute name="displayIf" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        <![CDATA[
          Conditional helpers which may define an xpath expression to evaluate if the xpath match.

        The scope of the expression is defined by a variable named "$p1" whitch is the current node.

        For example, to match a metadata on dataset:
        ```displayIf="$p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/gmd:MD_DataIdentification or
        $p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/*[@gco:isoType='gmd:MD_DataIdentification']"```

        and a metadata on service:
        ```displayIf="$p1/ancestor::node()[name()='gmd:MD_Metadata']/gmd:identificationInfo/srv:SV_ServiceIdentification"```

        or to test a value of the node
        ```displayIf="gco:CharacterString[contains(., 'temporal resolution: ')]"```

        The result of the displayIf XPath should be one or more nodes.
        It does not expect a boolean. For example, this does not work
        ```displayIf="gco:CharacterString/contains(., 'temporal resolution: ')"``` which return true or false.
          ]]>
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:element name="option">
    <xs:complexType mixed="true">
      <xs:attribute name="id" type="xs:NMTOKEN"/>
      <xs:attribute name="title"/>
      <xs:attribute name="value" use="required"/>
      <xs:attribute type="xs:boolean" name="default" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="inspireInfo" type="xs:string"/>

  <xs:element name="codelists">
    <xs:annotation>
      <xs:documentation>* Hide in edit mode : If some codelist needs to be
        hidden
        in edit mode, the hideInEditMode attribute could be added
        to any entries.

        eg.
        &lt;entry hideInEditMode="true">

        This will restrict the number of available entries for end
        user editors and keep all records ISO compatible when using
        codelist (eg. harvested records could use codelist hidden
        in local node and needs to be displayed in view mode).

        By default, this attribute is not used.

        * editorMode attribute allows to configure the editor form field.

        * - not set -: simple combo box
        * radio : radio button in one line
        * radio_linebreak : radio button with line break
        * radio_withdesc : radion button with line break and codelist entry
        description
        * select : select box with size set to the number of items if lower than
        7 entries.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded" minOccurs="0">
        <xs:element name="codelist">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
              <xs:element name="entry">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded">
                    <xs:element type="xs:string" name="code" maxOccurs="1" minOccurs="1"/>
                    <xs:element type="xs:string" name="label" maxOccurs="1" minOccurs="1"/>
                    <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="0"/>
                  </xs:choice>
                  <xs:attribute type="xs:boolean" name="hideInEditMode" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute ref="displayIf" use="optional" />
            <xs:attribute ref="sort" use="optional" />
            <xs:attribute type="xs:string" name="alias" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:attribute type="xs:string" name="sort" fixed="fixed">
    <xs:annotation>
      <xs:documentation>
        By default codelist are sorted in alphabetical order.
        Use this attribute to sort them by the order defined
        in the codelist definition file.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:schema>

=== geonetwork/core-geonetwork/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

 * Hide in edit mode : If some codelist needs to be hidden
 in edit mode, the hideInEditMode attribute could be added
 to any entries.

 eg.
	<entry hideInEditMode="true">

 This will restrict the number of available entries for end
 user editors and keep all records ISO compatible when using
 codelist (eg. harvested records could use codelist hidden
 in local node and needs to be displayed in view mode).

 By default, this attribute is not used.

 * editorMode attribute allows to configure the editor form field.

 * - not set -: simple combo box
 * radio : radio button in one line
 * radio_linebreak : radio button with line break
 * radio_withdesc : radion button with line break and codelist entry description
 * select : select box with size set to the number of items if lower than 7 entries.

-->
<codelists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0"
           xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0"
           xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0"
           xmlns:gex="http://standards.iso.org/iso/19115/-3/gex/1.0"
           xmlns:lan="http://standards.iso.org/iso/19115/-3/lan/1.0"
           xmlns:srv="http://standards.iso.org/iso/19115/-3/srv/2.1"
           xmlns:mas="http://standards.iso.org/iso/19115/-3/mas/1.0"
           xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0"
           xmlns:mco="http://standards.iso.org/iso/19115/-3/mco/1.0"
           xmlns:mda="http://standards.iso.org/iso/19115/-3/mda/1.0"
           xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
           xmlns:mds="http://standards.iso.org/iso/19115/-3/mds/2.0"
           xmlns:reg="http://standards.iso.org/iso/19135/-2/reg/1.0"
           xmlns:mdt="http://standards.iso.org/iso/19115/-3/mdt/2.0"
           xmlns:mex="http://standards.iso.org/iso/19115/-3/mex/1.0"
           xmlns:mmi="http://standards.iso.org/iso/19115/-3/mmi/1.0"
           xmlns:mpc="http://standards.iso.org/iso/19115/-3/mpc/1.0"
           xmlns:mrc="http://standards.iso.org/iso/19115/-3/mrc/2.0"
           xmlns:mrd="http://standards.iso.org/iso/19115/-3/mrd/1.0"
           xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
           xmlns:mrl="http://standards.iso.org/iso/19115/-3/mrl/2.0"
           xmlns:mrs="http://standards.iso.org/iso/19115/-3/mrs/1.0"
           xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
           xmlns:mdq="http://standards.iso.org/iso/19157/-2/mdq/1.0"
           xmlns:mac="http://standards.iso.org/iso/19115/-3/mac/2.0"
           xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
           xmlns:gml="http://www.opengis.net/gml/3.2"
           xmlns:xlink="http://www.w3.org/1999/xlink"
           xsi:noNamespaceSchemaLocation="../../../../../../../schema-labels.xsd">


  <codelist name="cit:CI_TelephoneTypeCode">
    <entry>
      <code>voice</code>
      <label>Voice</label>
      <description>Telephone provides voice service</description>
    </entry>
    <entry>
      <code>facsimilie</code>
      <label>Facsimilie</label>
      <description>Telephone provides facsimilie service</description>
    </entry>
    <entry>
      <code>sms</code>
      <label>SMS</label>
      <description>Telephone provides sms service</description>
    </entry>
  </codelist>
  <codelist name="cit:CI_DateTypeCode">
    <entry>
      <code>creation</code>
      <label>Creation</label>
      <description>Date identifies when the resource was brought into
        existence
      </description>
    </entry>
    <entry>
      <code>publication</code>
      <label>Publication</label>
      <description>Date identifies when the resource was issued</description>
    </entry>
    <entry>
      <code>revision</code>
      <label>Revision</label>
      <description>Date identifies when the resource was examined or re-examined
        and improved or amended
      </description>
    </entry>
    <entry>
      <code>expiry</code>
      <label>Expiry</label>
      <description>Date identifies when the resource expires</description>
    </entry>
    <entry>
      <code>lastUpdate</code>
      <label>Last Update</label>
      <description>Date identifies when the resource was last updated
      </description>
    </entry>
    <entry>
      <code>lastRevision</code>
      <label>Last Revision</label>
      <description>Date identifies when the resource was last reviewed
      </description>
    </entry>
    <entry>
      <code>nextUpdate</code>
      <label>Next Update</label>
      <description>Date identifies when the resource will be next updated
      </description>
    </entry>
    <entry>
      <code>unavailable</code>
      <label>Unavailable</label>
      <description>Date identifies when the resource became not available or
        obtainable
      </description>
    </entry>
    <entry>
      <code>inForce</code>
      <label>In Force</label>
      <description>Date identifies when the resource became in force
      </description>
    </entry>
    <entry>
      <code>adopted</code>
      <label>Adopted</label>
      <description>Date identifies when the resource was adopted</description>
    </entry>
    <entry>
      <code>deprecated</code>
      <label>Deprecated</label>
      <description>Date identifies when the resource was deprecated
      </description>
    </entry>
    <entry>
      <code>superseded</code>
      <label>Superseded</label>
      <description>Date identifies when the resource was superseded or replaced
        by another resource
      </description>
    </entry>
    <entry>
      <code>validityBegins</code>
      <label>Validity Begins</label>
      <description>Date identifies when the resource is considered to be valid
      </description>
    </entry>
    <entry>
      <code>validityExpires</code>
      <label>Validity Expires</label>
      <description>Date identifies when the resource is no longer considered to
        be valid
      </description>
    </entry>
    <entry>
      <code>released</code>
      <label>Released</label>
      <description>Date identifies when the resource shall be released for
        public access
      </description>
    </entry>
    <entry>
      <code>distribution</code>
      <label>Distribution</label>
      <description>Date identifies when an instance of the resource was
        distributed
      </description>
    </entry>
  </codelist>
  <codelist name="cit:CI_OnLineFunctionCode" alias="function">
    <entry>
      <code>download</code>
      <label>Download</label>
      <description>Online instructions for transferring data from one storage
        device or system to another
      </description>
    </entry>
    <entry>
      <code>information</code>
      <label>Information</label>
      <description>Online information about the resource</description>
    </entry>
    <entry>
      <code>offlineAccess</code>
      <label>Offline access</label>
      <description>Online instructions for requesting the resource from the
        provider
      </description>
    </entry>
    <entry>
      <code>order</code>
      <label>Order</label>
      <description>Online order process for obtening the resource</description>
    </entry>
    <entry>
      <code>search</code>
      <label>Search</label>
      <description>Online search interface for seeking out information about the
        resource
      </description>
    </entry>
    <entry>
      <code>completeMetadata</code>
      <label>Complete Metadata</label>
      <description>Complete metadata provided</description>
    </entry>
    <entry>
      <code>doi</code>
      <label>Digital Object Identifier (DOI)</label>
      <description></description>
    </entry>
    <entry>
      <code>browseGraphic</code>
      <label>Browse Graphic</label>
      <description>Browse Graphic provided</description>
    </entry>
    <entry>
      <code>upload</code>
      <label>Upload</label>
      <description>Upload service provided</description>
    </entry>
    <entry>
      <code>emailService</code>
      <label>Email Service</label>
      <description>Email service provided</description>
    </entry>
    <entry>
      <code>browsing</code>
      <label>Browsing</label>
      <description>Online browsing provided</description>
    </entry>
    <entry>
      <code>fileAccess</code>
      <label>Access File</label>
      <description>Online file access provided</description>
    </entry>
  </codelist>
  <codelist name="cit:CI_PresentationFormCode">
    <entry>
      <code>documentDigital</code>
      <label>Digital document</label>
      <description>Digital representation of a primarily textual item (can
        contain illustrations also)
      </description>
    </entry>
    <entry>
      <code>imageDigital</code>
      <label>Digital image</label>
      <description>Likeness of natural or man-made features, objects, and
        activities acquired through the sensing of visual or any other segment
        of the electromagnetic spectrum by sensors, such as thermal infrared,
        and high resolution radar and stored in digital format
      </description>
    </entry>
    <entry>
      <code>documentHardcopy</code>
      <label>Hardcopy document</label>
      <description>Representation of a primarily textual item (can contain
        illustrations also) on paper, photograhic material, or other media
      </description>
    </entry>
    <entry>
      <code>imageHardcopy</code>
      <label>Hardcopy image</label>
      <description>Likeness of natural or man-made features, objects, and
        activities acquired through the sensing of visual or any other segment
        of the electromagnetic spectrum by sensors, such as thermal infrared,
        and high resolution radar and reproduced on paper, photographic
        material, or other media for use directly by the human user
      </description>
    </entry>
    <entry>
